// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationPlatform.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MigrationPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709210236_AddLocalCredentials")]
    partial class AddLocalCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MigrationPlatform.Api.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ContentMigrationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUpn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SpoJobId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetOwnerUpn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("ContentMigrationItems", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ContentMigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MigratedItems")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpoMigrationJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WaveId");

                    b.ToTable("ContentMigrationJobs", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.DomainCutoverJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedUsers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsVerificationRecord")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("FailedUsers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetMxRecord")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DomainCutoverJobs", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.DomainRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourcePattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetPattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Priority");

                    b.ToTable("DomainRules", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.IdentityMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MappingSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetUpn")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IdentityMaps", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScanId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.LocalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("LocalCredentials", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MailboxMigrationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ExoMigrationBatchId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FailedMailboxes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SkippedMailboxes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("GraphCopy");

                    b.Property<int>("SyncedMailboxes")
                        .HasColumnType("integer");

                    b.Property<string>("TargetFolderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TotalMailboxes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WaveId");

                    b.ToTable("MailboxMigrationBatches", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MailboxMigrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("ItemsSyncedPercent")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessagesCopied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SourceUpn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetUpn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TotalMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("MailboxMigrationEntries", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MigrationProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SourceTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TargetTenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceTenantId");

                    b.HasIndex("TargetTenantId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MigrationWave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "Order");

                    b.ToTable("MigrationWaves", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Scans", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScanIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedObjectCount")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("RemediationSteps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScanIssues", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedDomains", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("MailEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SecurityEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedGroups", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedMailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ArchiveSizeGb")
                        .HasColumnType("double precision");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasArchive")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLogonTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MailboxType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PrimarySmtpAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<double>("SizeGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedMailboxes", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedOneDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DriveUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerUpn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<double>("StorageQuotaGb")
                        .HasColumnType("double precision");

                    b.Property<double>("StorageUsedGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedOneDrives", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasUniquePermissions")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("StorageQuotaGb")
                        .HasColumnType("double precision");

                    b.Property<double>("StorageUsedGb")
                        .HasColumnType("double precision");

                    b.Property<int>("SubsiteCount")
                        .HasColumnType("integer");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedSites", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccountEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasMailbox")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("Licenses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("MailboxSizeGb")
                        .HasColumnType("double precision");

                    b.Property<string>("MailboxType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("OneDriveSizeGb")
                        .HasColumnType("double precision");

                    b.Property<List<string>>("ProxyAddresses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Upn")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.ToTable("ScannedUsers", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminConsentGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("AppClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClientCertificateBase64")
                        .HasColumnType("text")
                        .HasColumnName("ClientCertificateBase64");

                    b.Property<string>("ClientCertificatePassword")
                        .HasColumnType("text")
                        .HasColumnName("ClientCertificatePassword");

                    b.Property<string>("ClientCertificateThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ClientCertificateThumbprint");

                    b.Property<string>("ClientSecretHint")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnMicrosoftDomain")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.UserMigrationBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrossTenantSyncJobId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CrossTenantSyncRuleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("FailedUsers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProvisionedUsers")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("DirectGraph");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WaveId");

                    b.ToTable("UserMigrationBatches", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.UserMigrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceUpn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetUpn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("UserMigrationEntries", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ValidationCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ValidationChecks", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PassedChecks")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalChecks")
                        .HasColumnType("integer");

                    b.Property<int>("WarningChecks")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WaveId");

                    b.ToTable("ValidationRuns", (string)null);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.AuditEvent", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ContentMigrationItem", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.ContentMigrationJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContentItems_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ContentMigrationJob", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContentJobs_Project");

                    b.HasOne("MigrationPlatform.Api.Models.MigrationWave", "Wave")
                        .WithMany("ContentJobs")
                        .HasForeignKey("WaveId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ContentJobs_Wave");

                    b.Navigation("Project");

                    b.Navigation("Wave");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.DomainCutoverJob", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DomainCutover_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.DomainRule", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DomainRules_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.IdentityMap", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.Job", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MailboxMigrationBatch", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MailboxBatches_Project");

                    b.HasOne("MigrationPlatform.Api.Models.MigrationWave", "Wave")
                        .WithMany("MailboxBatches")
                        .HasForeignKey("WaveId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_MailboxBatches_Wave");

                    b.Navigation("Project");

                    b.Navigation("Wave");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MailboxMigrationEntry", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MailboxMigrationBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MailboxEntries_Batch");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MigrationProject", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Tenant", "SourceTenant")
                        .WithMany()
                        .HasForeignKey("SourceTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_SourceTenant");

                    b.HasOne("MigrationPlatform.Api.Models.Tenant", "TargetTenant")
                        .WithMany()
                        .HasForeignKey("TargetTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Projects_TargetTenant");

                    b.Navigation("SourceTenant");

                    b.Navigation("TargetTenant");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MigrationWave", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MigrationWaves_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.Scan", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MigrationPlatform.Api.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("MigrationPlatform.Api.Models.ScanSummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("ScanId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BlockerCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_BlockerCount");

                            b1.Property<int>("DomainCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_DomainCount");

                            b1.Property<int>("GroupCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_GroupCount");

                            b1.Property<int>("MailboxCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_MailboxCount");

                            b1.Property<double>("MailboxTotalSizeGb")
                                .HasColumnType("double precision")
                                .HasColumnName("Summary_MailboxTotalSizeGb");

                            b1.Property<int>("OneDriveCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_OneDriveCount");

                            b1.Property<int>("ReadinessScore")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_ReadinessScore");

                            b1.Property<int>("SiteCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_SiteCount");

                            b1.Property<int>("UserCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_UserCount");

                            b1.Property<int>("WarningCount")
                                .HasColumnType("integer")
                                .HasColumnName("Summary_WarningCount");

                            b1.HasKey("ScanId");

                            b1.ToTable("Scans");

                            b1.WithOwner()
                                .HasForeignKey("ScanId");
                        });

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScanIssue", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedDomain", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedGroup", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedMailbox", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedOneDrive", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedSite", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ScannedUser", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.Scan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.UserMigrationBatch", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserMigrationBatches_Project");

                    b.HasOne("MigrationPlatform.Api.Models.MigrationWave", "Wave")
                        .WithMany("UserBatches")
                        .HasForeignKey("WaveId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UserMigrationBatches_Wave");

                    b.Navigation("Project");

                    b.Navigation("Wave");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.UserMigrationEntry", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.UserMigrationBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserMigrationEntries_Batch");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ValidationCheck", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.ValidationRun", "Run")
                        .WithMany("Checks")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ValidationChecks_Run");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ValidationRun", b =>
                {
                    b.HasOne("MigrationPlatform.Api.Models.MigrationProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ValidationRuns_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.MigrationWave", b =>
                {
                    b.Navigation("ContentJobs");

                    b.Navigation("MailboxBatches");

                    b.Navigation("UserBatches");
                });

            modelBuilder.Entity("MigrationPlatform.Api.Models.ValidationRun", b =>
                {
                    b.Navigation("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
